---
title: "mice_script"
author: "Irfan Ainuddin"
date: "5/8/2020"
output: html_document
---

```{r}
library(tidyverse)
library(mice)
```

```{r}
sd <- readRDS(file = "./data/clean_soil_data.rds")
```

## MICE
```{r}
round(mean(is.na(sd))*100, 2)

sd[,6:21] <- scale(sd[,6:21])
```
Twelve percent of this data is missing. 

```{r}
imp_sd <- mice(sd, m=30, maxit=25, seed=500, printFlag=FALSE)
summary(imp_sd)
```

```{r}
imp_sd$meth
```

```{r}
plot(imp_sd)
```

## Modeling Exchangable Sodium (ExchNa_ppm) and multiple imputation
```{r}
# with() use the imputed data set and run the model on every imputation (m=30)
model <- with(imp_sd, lm(ExchNa_ppm ~Date_Sampled +  Year + Irr_season + Field_ID + Soil_pH + Soluble_Salts + NO3_D1_ppm + Bicarb_P_ppm + SO4_ppm + ExchK_ppm + ExchCa_ppm + ExchMg_ppm + Zn_ppm + Mn_ppm + Cu_ppm + Boron_ppm + CEC_me_100g + treatment + Na_Sat_pct))

## pool() calculate pooled estimates using rubin's rules. 
mi.estimates <- summary(pool(model))
mi.estimates <- mi.estimates[-1,]

kable(pool(model)$pooled[c(1:4,8:9)], digits=3)
```

```{r}
## run model with regular data set, complete denotes the fact that the lm will drop any missing observations
complete.model <- lm(ExchNa_ppm ~ Date_Sampled + Year + Irr_season + Field_ID + Soil_pH + Soluble_Salts + NO3_D1_ppm + Bicarb_P_ppm + SO4_ppm + ExchK_ppm + ExchCa_ppm + ExchMg_ppm + Zn_ppm + Mn_ppm + Cu_ppm + Boron_ppm + CEC_me_100g + treatment + Na_Sat_pct, data = sd)


## extract beta estimates from the complete model.
betas <- c(coef(complete.model)[1:4], NA, coef(complete.model)[5:length(coef(complete.model))])
#remove the intercept estimates
betas <- betas[-1]

## calculate and bind the confidence interval, insert NA value for missing winter factor level, bind rest of the CI's
ci <- rbind(confint(complete.model)[1:4,], NA, confint(complete.model)[5:NROW(confint(complete.model)),])
#remove the intercept estimates
ci <- ci[-1,]

```

```{r}
## complete case (cc) multiple imputation model (mi)
cc.mean <- betas
mi.mean <- mi.estimates[,2]
## calcualte lower limit of CI
cc.ll   <- ci[,1]
mi.ll   <- mi.mean - 1.96*mi.estimates[,3]
## calcualte upper limit of NI
cc.ul   <- ci[,2]
mi.ul   <- mi.mean + 1.96*mi.estimates[,3]
# create names vector to use in forestplot. 
names   <- as.character(mi.estimates[,1])


#create forest plot to visualize variance between complete model and mice model
forestplot(names, 
           legend = c("Complete Model", "MICE"),
           fn.ci_norm = c(fpDrawNormalCI, fpDrawCircleCI), 
           mean = cbind(cc.mean, mi.mean), 
           lower = cbind(cc.ll, mi.ll),
           upper = cbind(cc.ul, mi.ul), 
           col=fpColors(box=c("blue", "darkred")), 
           xlab="Regression coefficients",
           boxsize = .1
           )
```


```{r}
## create a single data set from the imputed data sets (m=30, defined on imputation), action = (imputed_set_number)
# sd_imp <- complete(imp_sd, action=25)

## stacked data set, showing an observation 
#sd_imp_long <- complete(imp_sd, 'long')
```

```{r}
# names of columns
#names(sd_imp_long)
```


```{r}
##  show the number of observations for each imputation 
table(sd_imp_long$.imp)
```
~~30 Variables with a total of 828 observations.~~
30 imputed data sets with 838 observations in each data set.

```{r}
saveRDS(imp_sd, file = "./data/imputed_data.rds")
```

