---
title: "pcp_data_cleaning"
author: "Irfan Ainuddin"
date: "3/2/2020"
output: html_document
---
```{r}
library(tidyverse)
```

```{r get_data}
df <- read.csv("./data/pcp_soil_data/PCP-R-ready.csv")
```

```{r remove_na}
df2 <- df[, colSums(is.na(df)) != nrow(df)]
```

```{r select_vars}
df3 <- df2 %>% select("Date_Sampled","Year","Irr_season", "Depth_1", "Field_ID", "Soil_pH", "Buffer_pH", "Excess_Lime", "Soluble_Salts", "OM_pct", "NO3_D1_ppm", "NO3_D1_lbs_A", "NO3_Total_lbs_A", "NO3_Total_Depth", "Bicarb_P_ppm", "SO4_ppm", "ExchK_ppm", "ExchCa_ppm", "ExchMg_ppm", "ExchNa_ppm", "Zn_ppm", "Fe_ppm", "Mn_ppm", 'Cu_ppm', "Boron_ppm", "CEC_me_100g", "Base_Sat_pct", "H_Sat_pct", "Ca_Sat_pct", "Mg_Sat_pct", "K_Sat_pct", "Na_Sat_pct", "SOL_Ca_me_L", "SOL_Mg_me_L", "SAR", "ESP", "Gypsum_T_A", "NH4_D1_ppm", "NH4_D1_lbs_A", "Total_Nitrogen_pct", "xCrop_Name", "xCrop_Yield_Unit", "xRec_N_lbs_A", "xRec_P2O5_lbs_A", "xRec_K2O_lbs_A", "xRec_S_lbs_A", "xRec_Zn_lbs_A", "xRec_MgO_lbs_A", "xRec_Fe_lbs_A", "xRec_Mn_lbs_A", "xRec_Cu_lbs_A", "xRec_B_lbs_A")

```

```{r}

```


```{r recode_vars}

library(lubridate)

## set Date_Sampled from factor to Date
df3$Date_Sampled <- mdy(as.character(df3$Date_Sampled))

df3 <- data.frame(df3)
## set empty xCrop_Name to factor level to NA  datatype

## convert xCrop_yield_Unit

```

```{r Seperate_Depths}
low <- c()
high <- c()
for(i in 1:length(df3$Depth_1)){
  low <- c(low, strsplit(as.character(df3$Depth_1), "-")[[i]][1])
  high <- c(high, strsplit(as.character(df3$Depth_1), "-")[[i]][2])
}
df3$Depth_low <- low
df3$Depth_high <- high
```


```{r}
glimpse(head(df3))
```

```{r}
prop.miss <- apply(df3, 2, function(x) round(sum(is.na(x))/NROW(x),4))
prop.miss
```

```{r}
pmpv <- data.frame(variable = names(df3), pct.miss=prop.miss)

```

```{r}
ggplot(pmpv, aes(x= reorder(variable, pct.miss), y=pct.miss, fill=pct.miss)) +
  geom_bar(stat="identity") + 
  ggtitle("Missing Data") +
  ylab("Percent Missing") + 
  xlab("Variables") +
  scale_y_continuous(labels=scales::percent, limits=c(0,1.03)) + 
  geom_text(data=pmpv, aes(label=paste0(round(pct.miss*100,1),"%"), y=pct.miss+.03), size=2) +
  coord_flip() +
  theme(axis.text.y = element_text(size=5)) +
  scale_fill_gradient(low="darkturquoise",high="darkorchid3")
  
```


## inspect with MICE

```{r}
library(mice)
md.pattern(df3, rotate.names = TRUE)
```


## missing data with VIM

```{r}
library(VIM)
```

```{r}
aggr(df3, col=c('darkturquoise','darkorchid3'),
              numbers=TRUE, sortVars=TRUE, prop=TRUE,border=TRUE, combined=TRUE,
              labels=names(df3), cex.axis=.4, cex.numbers=.4, varheight=FALSE,
              gap=0, ylab=c("Missing data","Pattern"))
```


```{r}
library(psych)
```

```{r}
## Correlation matrix betwen Macronutrients

pairs.panels(df3[,17:20],
             method="pearson",
             hist.col="#00ced1",
             density=TRUE,
             ellipses = TRUE,
             cex.labels = 1.2,
             )
```

```{r}
# Correation Matrix between micronutrients 

pairs.panels(df3[,21:25],
             method="pearson",
             hist.col="#9a32cd",
             density=TRUE,
             ellipses = TRUE,
             cex.labels = 1.2,
             )
```


```{r}
# Correation Matrix between micronutrients 

pairs.panels(df3[,14:24],
             method="pearson",
             hist.col="#65cd32",
             density=TRUE,
             ellipses = TRUE,
             cex.labels = 1.2,
             )
```

```{r}
pairs(df3[,16:19], pch=19)
```


```{r}
ggplot(df3, aes(x=Date_Sampled)) + 
  geom_point(aes(y=ExchNa_ppm), color="blue") +
  geom_point(aes(y=ExchK_ppm), color="darkorchid3") +
  geom_smooth(aes(y=ExchNa_ppm), color="darkturquoise") +
  geom_smooth(aes(y=ExchK_ppm), color="darkorchid3") +
  labs(x="Sampling Date",y="Parts per Million (ppm)",title="Exchangeable Macronutrients")
```

```{r}
ggplot(df3, aes(x=Date_Sampled)) + 
  geom_point(aes(y=Na_Sat_pct), color="blue") +
  geom_point(aes(y=K_Sat_pct), color="darkorchid3") +
  geom_smooth(aes(y=Na_Sat_pct), color="darkturquoise") +
  geom_smooth(aes(y=K_Sat_pct), color="darkorchid3") +
  labs(x="Sampling Date",y="Percent Saturation (%)",title="Exchangeable Macronutrients")
```



```{r}
df4 <- df3 %>% select("Date_Sampled","Year","Irr_season", "Depth_1", "Field_ID", "Soil_pH", "Soluble_Salts", "OM_pct", "NO3_D1_ppm", "Bicarb_P_ppm", "SO4_ppm", "ExchK_ppm", "ExchCa_ppm", "ExchMg_ppm", "ExchNa_ppm", "Zn_ppm", "Fe_ppm", "Mn_ppm", 'Cu_ppm', "Boron_ppm", "CEC_me_100g")


```


```{r}
df4 <- mutate(df4, treatment = ifelse( Year < 2013, "Sodium","Potassium"))
df4$treatment <- as.factor(df4$treatment)

#sd_imp <- mutate(sd_imp, treatment = ifelse( Year < 2013, "Sodium","Potassium"))
#sd_imp$treatment <- as.factor(sd_imp$treatment)


```

```{r}
## save working data set
saveRDS(df4, file = "./data/clean_soil_data.rds")

## save longer working data set  for other_scripts.
saveRDS(df3, file="./data/other_clean_soil_data.rds")

```



